Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 1
    end
  
    # Указываем имена хостов и их IP-адреса
    boxes = [
      { :name => "ipa.otus.lan",
        :ip => "192.168.56.10",
      },
      { :name => "client1.otus.lan",
        :ip => "192.168.56.11",
      },
      { :name => "client2.otus.lan",
        :ip => "192.168.56.12",
      }
    ]

   
    boxes.each do |opts|
      config.vm.define opts[:name] do |box_config|
        box_config.vm.hostname = opts[:name]
        box_config.vm.network "private_network", ip: opts[:ip]
        
        
        box_config.vm.provision "shell", inline: <<-SHELL
          sed -i 's/mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's/#baseurl/baseurl/g' /etc/yum.repos.d/CentOS-Base.repo
          sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/CentOS-Base.repo
        SHELL

        
        if opts[:name] == "client2.otus.lan"
          box_config.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.inventory_path = "ansible/hosts"
            ansible.host_key_checking = "false"
            ansible.limit = "all" 
            ansible.become = "true"
          end
        end
      end
    end
end
