---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.255.6/30
      optional: false
      routes:
        - to: default
          via: 192.168.255.5
    enp0s9:
      addresses:
      - 192.168.1.1/25
      optional: false
    enp0s10:
      addresses:
      - 192.168.1.129/26
      optional: false
    enp0s16:
      addresses:
      - 192.168.1.193/26
      optional: false
    enp0s19:
      addresses:
      - 192.168.56.30/24
      optional: false
