Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Настройка виртуальной машины для сервера NFS
  config.vm.define "nfs_server" do |server|
    server.vm.hostname = "nfs-server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nfs-kernel-server
      mkdir -p /var/nfs/general/upload
      chown nobody:nogroup /var/nfs/general/upload
      chmod 777 /var/nfs/general/upload
      echo "/var/nfs/general 192.168.56.0/24(rw,sync,no_subtree_check)" | sudo tee /etc/exports
      sudo exportfs -ra
      sudo systemctl restart nfs-kernel-server
    SHELL
  end

  # Настройка виртуальной машины для клиента NFS
  config.vm.define "nfs_client" do |client|
    client.vm.hostname = "nfs-client"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    client.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nfs-common
      mkdir -p /mnt/nfs/general
      echo "192.168.56.10:/var/nfs/general /mnt/nfs/general nfs vers=3,proto=tcp,rw 0 0" | sudo tee -a /etc/fstab
      sudo mount -a
    SHELL
  end
end
