Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    # Добавляем shell провижининг для установки Python
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y python3
        # Создаем симлинк, если ansible ожидает python в /usr/bin/python
        if [ ! -f /usr/bin/python ]; then
            sudo ln -s /usr/bin/python3 /usr/bin/python
        fi
    SHELL

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.become = true
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "server" do |server|
        server.vm.network "private_network", ip: "192.168.56.12"
        server.vm.hostname = "server"
    end

    config.vm.define "client" do |client|
        client.vm.network "private_network", ip: "192.168.56.13"
        client.vm.hostname = "client"
    end
end
