Vagrant.configure("2") do |config|
    
    
    config.vm.define "debian_vm" do |debian|
      debian.vm.box = "Debian-10"  
      debian.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "1"
        v.vmx["scsi0:0.present"] = "TRUE"
        v.vmx["scsi0:0.fileName"] = "disk.vmdk"
        v.vmx["scsi0:0.capacity"] = "30720"
      end
      debian.vm.network "public_network"
      debian.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y sudo ufw
        useradd -m -s /bin/bash pt && echo "Пользователь pt успешно создан."
        echo 'pt:123' | chpasswd && echo "Пароль для pt успешно изменен."
        usermod -aG sudo pt && echo "Пользователь pt добавлен в группу sudo."
        ufw allow 22
        ufw allow 8080
        ufw --force enable && echo "UFW включен и настроен."
      SHELL
    end
  
    
    
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.groups = {
          "all" => ["debian_vm"]
        }
        ansible.limit = "all"
        ansible.verbose = "v"
      end
  
  end
  