# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :selinux => {
    :box_name => "almalinux/9",
    :box_version => "0",
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = "selinux"
      box.vm.network "forwarded_port", guest: 4881, host: 4881
      box.vm.network "private_network", ip: "192.168.56.10"

      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        # needsController = false
      end

      box.vm.provision "shell", inline: <<-SHELL
        # Установка epel-release
        yum install -y epel-release
        # Установка nginx
        yum install -y nginx
        # Изменение порта nginx
        sed -ie 's/:80/:4881/g' /etc/nginx/nginx.conf
        sed -i 's/listen       80;/listen       4881;/' /etc/nginx/nginx.conf
        # Отключение SELinux 
        # setenforce 0
        # Запуск nginx
        systemctl start nginx
        systemctl status nginx
        # Проверка порта nginx
        ss -tlpn | grep 4881
      SHELL
    end
  end
end
